// === 手相占いデータ ===
// 手相占い機能を実装するための完全データセット

// === 1. 手の形（エレメント分類） ===
const handTypes = {
  earth: {
    name: "土の手",
    nameEn: "Earth Hand",
    condition: "四角い手のひら × 短い指",
    traits: ["現実的", "実務的", "安定志向", "忍耐強い", "誠実", "勤勉"],
    description: "穏やかで落ち着きがあり、具体的で実用的なものに重きを置く。粘り強く最終的に大きな仕事をやり遂げる。世渡りは上手ではないが誠実で人間関係は良好。",
    workSuitable: ["実務", "農業", "建築", "製造", "管理職"],
    loveStyle: "誠実で一途。安定した関係を築く。",
    luckyColor: "アースカラー（茶・緑）",
  },
  fire: {
    name: "火の手",
    nameEn: "Fire Hand",
    condition: "長方形の手のひら × 短い指",
    traits: ["情熱的", "行動力", "エネルギッシュ", "リーダーシップ", "率直", "社交的"],
    description: "情熱を持ち、全力で取り組む。率直で社交性があり、親分肌でリーダー向き。その場の空気を変える力がある。",
    workSuitable: ["起業", "営業", "芸能", "スポーツ", "リーダー職"],
    loveStyle: "情熱的で積極的。一目惚れしやすい。",
    luckyColor: "レッド・オレンジ",
  },
  air: {
    name: "風の手",
    nameEn: "Air Hand",
    condition: "四角い手のひら × 長い指",
    traits: ["知的", "社交的", "合理的", "分析的", "好奇心旺盛", "客観的"],
    description: "固定概念にとらわれず合理的に考える。社交的で話好き。知的好奇心が原動力。物事を割り切る頭の良さがビジネスで強み。",
    workSuitable: ["IT", "研究", "教育", "コンサル", "マスコミ"],
    loveStyle: "知的な会話を重視。パートナーには頭の良さを求める。",
    luckyColor: "イエロー・ライトブルー",
  },
  water: {
    name: "水の手",
    nameEn: "Water Hand",
    condition: "長方形の手のひら × 長い指",
    traits: ["感受性豊か", "直感的", "想像力", "協調性", "繊細", "共感的"],
    description: "イマジネーション豊かで、夢や想像の世界に生きる。スピリチュアルな能力を持つことも。繊細で共感的だが流されやすい。",
    workSuitable: ["芸術", "デザイン", "心理", "医療", "スピリチュアル"],
    loveStyle: "深い絆を求める。ロマンチスト。",
    luckyColor: "ブルー・パープル",
  },
};

// === 2. 基本4線 + 補助線 ===
const palmLines = {
  // --- 4大基本線 ---
  lifeLine: {
    name: "生命線",
    nameEn: "Life Line",
    position: "親指と人差し指の間から手首に向かって弧を描く線",
    meaning: "生命力、健康状態、体力、人生のバイタリティ",
    note: "長さ＝寿命ではない。線の濃さ・ハリ・弧の大きさが重要。",
    variations: {
      "long_deep": { desc: "長く濃い", meaning: "体力があり健康的。生命力が強い。人生に自信を持っている。", rating: "good" },
      "short": { desc: "短い", meaning: "集中型のエネルギー配分。短いからといって寿命が短いわけではない。", rating: "neutral" },
      "wide_arc": { desc: "大きな弧", meaning: "金星丘を大きく囲む。人生を大きく生きたい欲求。温かく磁力のある人柄。", rating: "good" },
      "narrow_arc": { desc: "小さな弧", meaning: "安定した生活を求める。控えめで堅実。", rating: "neutral" },
      "broken": { desc: "切れている", meaning: "人生の大きな転機。生命力の弱まり。内側に切れる→困難が長引く、外側に切れる→困難を乗り越えられる。", rating: "caution" },
      "island": { desc: "島がある", meaning: "要注意期間。健康面の低下。エネルギーの停滞。（起点付近の島は解剖学的にできやすいので気にしなくていい）", rating: "caution" },
      "double": { desc: "二重生命線", meaning: "生命力が2倍。非常にタフ。困難から守られる。", rating: "good" },
      "chain": { desc: "鎖状", meaning: "体質が繊細。心身の揺れやすさ。", rating: "caution" },
      "faint": { desc: "薄い・弱い", meaning: "まだ自分の道を模索中。エネルギーが安定していない。", rating: "neutral" },
      "branch_up_jupiter": { desc: "上向き枝（人差し指方向）", meaning: "向上線（努力線）。向上心があり努力が実る。問題に前向きに立ち向かう。", rating: "good" },
      "branch_up_sun": { desc: "上向き枝（薬指方向）", meaning: "太陽線への枝。金運・魅力の開花。", rating: "good" },
      "branch_up_mercury": { desc: "上向き枝（小指方向）", meaning: "財運線への枝。お金の管理能力。", rating: "good" },
      "branch_down": { desc: "下向きの弱い枝", meaning: "体力・気力の衰え。注意サイン。（はっきりした下向き線は旅行線で吉）", rating: "caution" },
      "mote_branches": { desc: "短い2本が上向き", meaning: "モテ線。異性からの人気が高い。魅力的なオーラ。", rating: "good" },
      "mars_line": { desc: "内側に副線（火星線）", meaning: "一番充実している時期・勝負の時期を示す。隠れた生命力の予備。", rating: "good" },
      "fish_mark": { desc: "魚紋（フィッシュ）", meaning: "幸運の兆し。生命力・健康運アップ。", rating: "good" },
      "star_mark": { desc: "星紋（スター）", meaning: "突然の幸運や変化。", rating: "good" },
      "cross_mark": { desc: "十字紋", meaning: "試練やトラブルの暗示。", rating: "caution" },
      "square_mark": { desc: "四角紋（スクエア）", meaning: "守護。困難から守られる。", rating: "good" },
      "triangle_mark": { desc: "三角紋", meaning: "才能の開花。", rating: "good" },
    },
  },

  headLine: {
    name: "知能線（頭脳線）",
    nameEn: "Head Line",
    position: "人差し指の付け根付近から手のひらを横切る線",
    meaning: "思考パターン、知性のタイプ、判断力、才能の方向性",
    note: "頭の良し悪しではなく、思考のクセや能力の方向性を読む。",
    variations: {
      "long_straight": { desc: "長くまっすぐ", meaning: "論理的で記憶力が鋭い。熟考型。分析的思考。", rating: "neutral" },
      "long_deep": { desc: "長く濃い", meaning: "明確で集中した思考。思考力が高い。", rating: "good" },
      "short": { desc: "短い", meaning: "直感的でスピーディーなタイプ。即断即決。身体的達成を重視。", rating: "neutral" },
      "curved_down": { desc: "下にカーブ", meaning: "創造的で革新的。想像力豊か。文学やファンタジーを好む。", rating: "neutral" },
      "curved_sharp_down": { desc: "急激に下カーブ", meaning: "悲観的になりやすい傾向。", rating: "caution" },
      "curved_up": { desc: "上にカーブ（小指方向）", meaning: "数学・ビジネス・論理に得意。", rating: "good" },
      "straight": { desc: "まっすぐ", meaning: "現実的で実用的な思考。", rating: "neutral" },
      "wavy": { desc: "波状", meaning: "集中力が短い。注意力が散漫になりやすい。", rating: "caution" },
      "faint": { desc: "薄い", meaning: "集中困難や記憶力の弱さ。", rating: "caution" },
      "joined_life": { desc: "生命線と接続", meaning: "慎重で感受性が強い。", rating: "neutral" },
      "separated_life": { desc: "生命線と離れている", meaning: "独立心が強い。冒険心と人生への熱意。", rating: "neutral" },
      "forked": { desc: "二股（ライターズフォーク）", meaning: "論理と想像力の両方を持つ。文章力に優れる。", rating: "good" },
      "double": { desc: "二重知能線", meaning: "知的能力が2倍。多才。", rating: "good" },
      "simian": { desc: "感情線と一体化（ますかけ）", meaning: "強運。集中力と意志が強い。天下取りの相。", rating: "good" },
    },
  },

  heartLine: {
    name: "感情線",
    nameEn: "Heart Line",
    position: "小指の下から人差し指方向に伸びる線",
    meaning: "感情表現、恋愛パターン、人との関わり方、感受性",
    note: "恋愛傾向や他人への接し方がわかる。カーブが大きいほど感情豊か。",
    variations: {
      "long_curved": { desc: "長くカーブ", meaning: "感情豊かで表現がオープン。自由に感情を表す。", rating: "good" },
      "long": { desc: "長い", meaning: "ロマンチックなコミットメントが多い。感情が深い。", rating: "neutral" },
      "short": { desc: "短い", meaning: "恋愛への関心が薄い、または選択的。プライベート。", rating: "neutral" },
      "straight": { desc: "まっすぐ", meaning: "クールで現実的。感情を行動で示すタイプ。", rating: "neutral" },
      "straight_parallel": { desc: "知能線と平行でまっすぐ", meaning: "感情知能が高く実用的。", rating: "good" },
      "wavy": { desc: "波状", meaning: "多くの関係があるが深いコミットメントに欠ける。", rating: "caution" },
      "deep": { desc: "濃い", meaning: "一途な心。深い愛情。", rating: "good" },
      "faint": { desc: "薄い", meaning: "移り気な心。感情が安定しにくい。", rating: "caution" },
      "ends_index": { desc: "人差し指の下で終わる", meaning: "恋愛生活に満足している。理想主義的。", rating: "good" },
      "ends_middle": { desc: "中指の下で終わる", meaning: "恋愛において自分勝手な傾向。", rating: "caution" },
      "ends_between": { desc: "人差し指と中指の間で終わる", meaning: "恋愛に対して理解のある態度。バランス型。", rating: "good" },
      "touches_life": { desc: "生命線に触れる", meaning: "心が折れやすい。傷つきやすい。", rating: "caution" },
      "broken": { desc: "切れている", meaning: "感情的トラウマ。心の傷。浮気や別れの経験。", rating: "caution" },
      "circle": { desc: "丸い印（サークル）", meaning: "悲しみやすい、うつ傾向。", rating: "caution" },
      "chain": { desc: "鎖状", meaning: "感情的複雑さ。繊細な感情の波。", rating: "caution" },
      "upward_branches": { desc: "上向きの枝が複数（モテ線）", meaning: "魅力的なオーラ。異性からの人気が高い。", rating: "good" },
      "to_jupiter_gap": { desc: "人差し指と中指の間へ長く伸びる（玉の輿線）", meaning: "経済力のあるパートナーとの縁が強い。", rating: "good" },
      "forked": { desc: "二股・三股", meaning: "感情の多角性。複数の恋愛の可能性。", rating: "neutral" },
      "double": { desc: "二重感情線", meaning: "感受性が2倍。非常に情緒豊か。", rating: "neutral" },
    },
  },

  fateLine: {
    name: "運命線",
    nameEn: "Fate Line",
    position: "手首付近から中指に向かって縦に伸びる線",
    meaning: "仕事運、社会的な成功、人生の方向性、運命の流れ",
    note: "ない人もいる。ない＝「レールに縛られない自由な生き方」と読む。",
    variations: {
      "deep_clear": { desc: "濃くはっきり", meaning: "自分の道をしっかり歩んでいる。明確な運命。社会的成功。", rating: "good" },
      "faint": { desc: "薄い", meaning: "自分で運命を切り開くタイプ。自由な人生。", rating: "neutral" },
      "absent": { desc: "ない", meaning: "自発的な人生、または方向性を必要としている状態。縛られない自由な生き方。", rating: "neutral" },
      "broken_overlap": { desc: "切れて重なる", meaning: "変化が前進をもたらす。キャリアの転換。", rating: "neutral" },
      "broken_pieces": { desc: "いくつにも切れる", meaning: "キャリアが中断されやすい。波乱の人生。", rating: "caution" },
      "from_wrist": { desc: "手首から始まる", meaning: "早くから天職に目覚める。", rating: "good" },
      "from_moon_mount": { desc: "月丘から始まる", meaning: "公的な仕事。人々に影響を与える人生。", rating: "good" },
      "from_life_line": { desc: "生命線から始まる", meaning: "自力で成功するタイプ。", rating: "good" },
      "from_middle": { desc: "手のひら中央から始まる", meaning: "遅咲きタイプ。中年以降に開花。", rating: "neutral" },
      "to_index": { desc: "人差し指方向へ", meaning: "リーダーシップ・野心の方向性。", rating: "good" },
      "to_ring": { desc: "薬指方向へ", meaning: "芸術・人気運の方向性。", rating: "good" },
      "forked": { desc: "二股・三股", meaning: "複数の道を持つ。多角的な活動。", rating: "good" },
      "double": { desc: "二重運命線", meaning: "社会的責任が2倍。2つの道を歩む。", rating: "good" },
    },
  },

  // --- 補助線 ---
  sunLine: {
    name: "太陽線（成功線）",
    nameEn: "Sun Line",
    position: "薬指の付け根に向かう縦線",
    meaning: "名声、人気、芸術的成功、評価、才能の開花",
    note: "細くてもあること自体が吉相。",
    variations: {
      "present_clear": { desc: "ある・濃い", meaning: "人気運・成功運が強い。注目される才能。", rating: "good" },
      "absent": { desc: "ない", meaning: "目立たなくても地道に成功するタイプ。", rating: "neutral" },
      "multiple": { desc: "複数ある", meaning: "複数の分野で成功する可能性。", rating: "good" },
      "forked": { desc: "二股・三股", meaning: "多方面での評価。多才。", rating: "good" },
      "star": { desc: "星紋がある", meaning: "突然の成功や幸運。人気爆発。", rating: "good" },
      "from_fate": { desc: "運命線から出る", meaning: "仕事を通じて評価・成功を得る。", rating: "good" },
      "from_life": { desc: "生命線から出る", meaning: "努力によって才能が開花。", rating: "good" },
      "from_heart": { desc: "感情線から出る", meaning: "感情豊かさが才能に直結。芸術向き。", rating: "good" },
    },
  },

  wealthLine: {
    name: "財運線",
    nameEn: "Wealth Line",
    position: "小指の付け根にある短い縦線",
    meaning: "お金を稼ぐ才能、金銭感覚、実行力",
    note: "くっきりしているほど金運が強い。3cm以内のピンとした線が理想。",
    variations: {
      "one_clear": { desc: "1本はっきり", meaning: "金銭管理能力が高い。堅実に稼ぐ。", rating: "good" },
      "multiple": { desc: "複数ある", meaning: "複数の収入源を持つ。多角的な稼ぎ手。", rating: "good" },
      "long": { desc: "長い（感情線を超える）", meaning: "自分で起業して成功する能力。稼ぐ力が強い。", rating: "good" },
      "straight": { desc: "ピンとまっすぐ", meaning: "理想の財運線。金運安定。", rating: "good" },
      "wavy": { desc: "クネクネ曲がる", meaning: "収入や支出が安定しにくい。金銭の波あり。", rating: "caution" },
      "crossed_end": { desc: "先端に横線が付く", meaning: "金銭的な不運。お金の流れが止まる。", rating: "caution" },
      "island": { desc: "島がある", meaning: "金運の停滞。貯まりにくい時期。", rating: "caution" },
      "from_fate": { desc: "運命線から出る", meaning: "仕事の成功で収入アップ。出世運。", rating: "good" },
      "joins_sun": { desc: "太陽線と交わる", meaning: "人気と金運の両立。各方面で成功。", rating: "good" },
      "joins_marriage": { desc: "結婚線と合流", meaning: "結婚を機に財産を得る。玉の輿・逆玉。", rating: "good" },
    },
  },

  marriageLine: {
    name: "結婚線",
    nameEn: "Marriage Line",
    position: "小指の付け根と感情線の間にある短い横線",
    meaning: "結婚、重要なパートナーシップ、恋愛のチャンス",
    note: "本数＝結婚回数ではなくチャンスの回数。感情線に近いほど早婚、小指に近いほど晩婚。",
    variations: {
      "one_deep": { desc: "1本濃い", meaning: "一途な恋愛・結婚。深い絆。運命的な大恋愛。", rating: "good" },
      "two_three": { desc: "2〜3本", meaning: "結婚のチャンスが複数回。一般的な本数。", rating: "neutral" },
      "four_plus": { desc: "4本以上", meaning: "恋愛経験が豊富。モテるが一人に絞りにくい。", rating: "neutral" },
      "zero": { desc: "ない", meaning: "現在結婚への関心が薄い。気持ちが変われば現れる。", rating: "neutral" },
      "long_clear": { desc: "長くはっきり", meaning: "結婚運が強い。良い結婚に恵まれる。", rating: "good" },
      "short": { desc: "短い", meaning: "結婚への関心が薄い、または恋愛を楽しむタイプ。", rating: "neutral" },
      "upward": { desc: "上向きにカーブ", meaning: "幸せな結婚生活。パートナーと相性良好。大吉相。", rating: "good" },
      "downward": { desc: "下向きにカーブ", meaning: "結婚生活への不満。愛情の冷え込み。", rating: "caution" },
      "horizontal": { desc: "ほぼ水平", meaning: "円満な結婚生活。安定した関係。", rating: "good" },
      "forked": { desc: "二股に分かれる", meaning: "離婚やパートナーとの距離の暗示。", rating: "caution" },
      "chain": { desc: "鎖状", meaning: "結婚生活に波がある。苦労はあるが絆が深まる。", rating: "caution" },
      "to_sun": { desc: "太陽線に到達（玉の輿線）", meaning: "結婚によって社会的成功・財運がもたらされる。", rating: "good" },
      "up_jump": { desc: "先端が上に跳ね上がる", meaning: "玉の輿の暗示。経済的に恵まれた結婚。", rating: "good" },
      "island": { desc: "島がある", meaning: "結婚に関するトラブルや停滞。", rating: "caution" },
      "fish": { desc: "魚紋がある", meaning: "大幸運。素晴らしいパートナーに恵まれる。", rating: "good" },
      "star": { desc: "星紋がある", meaning: "理想の相手との出会い。予期せぬ幸運な結婚。", rating: "good" },
    },
  },

  healthLine: {
    name: "健康線",
    nameEn: "Health Line",
    position: "手首近くから小指方向に斜めに伸びる線",
    meaning: "健康状態、特に内臓や消化器系の強さ",
    note: "ない方が健康とされる。ある場合は健康への注意が必要。",
    variations: {
      "absent": { desc: "ない", meaning: "健康状態が良好。特に問題なし。", rating: "good" },
      "clear": { desc: "はっきりしている", meaning: "健康への意識が高い。自己管理ができる。", rating: "neutral" },
      "broken": { desc: "切れている", meaning: "健康に波がある。注意が必要な時期。", rating: "caution" },
      "island": { desc: "島がある", meaning: "健康問題の停滞。慢性化の可能性。", rating: "caution" },
      "wavy": { desc: "波状", meaning: "体調が安定しにくい。消化器系に注意。", rating: "caution" },
    },
  },

  travelLine: {
    name: "旅行線",
    nameEn: "Travel Line",
    position: "手首近くの生命線の反対側から横に伸びる線",
    meaning: "海外旅行、移住、グローバルな活躍",
    variations: {
      "present": { desc: "ある", meaning: "旅行や移住との縁がある。グローバルに活躍する可能性。", rating: "good" },
      "multiple": { desc: "複数ある", meaning: "海外縁が強い。国際的な活躍。", rating: "good" },
      "absent": { desc: "ない", meaning: "地元で安定することを好む。", rating: "neutral" },
    },
  },
};

// === 3. 特殊線・紋 ===
const specialMarks = {
  simianLine: {
    name: "ますかけ線",
    nameEn: "Simian Line",
    position: "知能線と感情線が一本につながった線",
    meaning: "強運、集中力、リーダーシップ、天才的なアイデアマン",
    rarity: "約5%程度（100人に1人とも）",
    description: "感情と理性が一体化した判断力。つかんだ運は絶対に離さない。「天下取りの相」とも呼ばれる。コミュニケーション力に優れ、人を惹きつける。",
    leftHand: "生まれ持った強運・才能",
    rightHand: "努力で掴んだ強運",
    bothHands: "最強の強運",
  },
  luckyM: {
    name: "ラッキーM線（M字手相）",
    nameEn: "Lucky M",
    position: "4大線がMの形に重なる",
    meaning: "幸運、バランスの良さ、総合的な成功",
    rarity: "稀少",
    description: "生命線・知能線・感情線・運命線がMの字に交わる稀少な相。全体的なバランスが良く、多方面で成功する可能性。",
  },
  mysticCross: {
    name: "神秘十字線",
    nameEn: "Mystic Cross",
    position: "知能線と感情線の間・手のひら中央の十字",
    meaning: "直感力、霊感、感受性の強さ、守護",
    rarity: "数百人〜数千人に1人",
    description: "現実世界と精神世界の両方で卓越した能力。スピリチュアルな才能。",
  },
  buddhaEye: {
    name: "仏眼相",
    nameEn: "Buddha Eye",
    position: "親指の第一関節の目のようなしわ",
    meaning: "直感力、記憶力、洞察力",
    rarity: "稀少",
    description: "仏の眼を持つと言われる稀少な相。直感力と記憶力に優れる。",
  },
  fatimaEye: {
    name: "ファティマの目",
    nameEn: "Eye of Fatima",
    position: "手のひらに現れる目の形の紋",
    meaning: "知性と霊性の象徴、邪気払い",
    rarity: "稀少",
    description: "知性と霊性を兼ね備えた稀少な相。",
  },
  solomonRing: {
    name: "ソロモンの環",
    nameEn: "Ring of Solomon",
    position: "人差し指の付け根を囲む半円の線",
    meaning: "人望、リーダーシップ、洞察力",
    rarity: "やや稀少",
    description: "人を惹きつける力が強い。リーダーシップに優れ、人望がある。",
  },
  fishMark: {
    name: "魚紋（フィッシュ）",
    nameEn: "Fish Mark",
    position: "線上に現れる魚型の紋",
    meaning: "幸運、金運が近づく、豊かさ",
    rarity: "稀少",
    description: "線上に魚の形に見える紋。幸運の印。出る位置によって意味が変わる。",
  },
  starMark: {
    name: "星紋（スター）",
    nameEn: "Star Mark",
    position: "線上や丘に現れる星形の紋",
    meaning: "突然の幸運、成功、好機",
    rarity: "やや稀少",
    description: "3本以上の短い線が一点で交差して星のように見える紋。出る丘によって意味が変わる（太陽丘＝成功、木星丘＝リーダーシップ）。",
  },
  crossMark: {
    name: "十字紋（クロス）",
    nameEn: "Cross Mark",
    position: "線が交差する印",
    meaning: "試練、トラブル、注意のサイン（神秘十字線を除く）",
    rarity: "普通",
    description: "線が交差してできる十字印。基本的には注意のサイン。",
  },
  islandMark: {
    name: "島（アイランド）",
    nameEn: "Island",
    position: "線上の楕円形の模様",
    meaning: "エネルギーの停滞、疲れ、要注意期間",
    rarity: "普通",
    description: "線の途中にできる小さな輪。休息やケアが必要なサイン。一時的なものが多い。",
  },
  squareMark: {
    name: "四角紋（スクエア）",
    nameEn: "Square Mark",
    position: "線上や丘に現れる四角の紋",
    meaning: "守護、困難から守られる",
    rarity: "やや稀少",
    description: "困難な時期に現れる守護の印。悪い意味を和らげる。",
  },
  triangleMark: {
    name: "三角紋",
    nameEn: "Triangle Mark",
    position: "線上や丘に現れる三角の紋",
    meaning: "才能の開花、知性の向上",
    rarity: "やや稀少",
    description: "才能と知性を示す吉相。",
  },
  hegemonLine: {
    name: "覇王線（三奇紋）",
    nameEn: "Hegemon Line",
    position: "運命線・太陽線・財運線が1点から始まる",
    meaning: "志・評価・お金が同じ方向へ向かう大成功",
    rarity: "非常に稀少",
    description: "三本の縦線がきれいにそろう稀少な相。桁外れの成功と影響力を示す。",
  },
};

// === 4. 手のひらの丘（マウント） ===
const mounts = {
  jupiter: {
    name: "木星丘",
    nameEn: "Mount of Jupiter",
    position: "人差し指の付け根",
    meaning: "野心、リーダーシップ、向上心",
    fullDesc: "張りがあるほどリーダーシップと向上心が強い。野心家で目標達成力がある。",
    flatDesc: "張りが乏しいと自信不足や受動的な傾向。",
  },
  saturn: {
    name: "土星丘",
    nameEn: "Mount of Saturn",
    position: "中指の付け根",
    meaning: "忍耐、責任感、学問、思慮深さ",
    fullDesc: "張りがあるほど忍耐力と責任感が強い。コツコツ積み上げる力。",
    flatDesc: "張りが乏しいと責任感が薄い、飽きっぽい傾向。",
  },
  sun: {
    name: "太陽丘",
    nameEn: "Mount of Sun",
    position: "薬指の付け根",
    meaning: "才能、人気、芸術性、成功運",
    fullDesc: "張りがあるほど人気と才能がある。芸術的センスに恵まれる。",
    flatDesc: "張りが乏しいと目立つことを避ける傾向。",
  },
  mercury: {
    name: "水星丘",
    nameEn: "Mount of Mercury",
    position: "小指の付け根",
    meaning: "商才、コミュニケーション、財運",
    fullDesc: "張りがあるほど商才とコミュ力がある。金銭感覚に優れる。",
    flatDesc: "張りが乏しいと表現力に欠ける傾向。",
  },
  venus: {
    name: "金星丘",
    nameEn: "Mount of Venus",
    position: "親指の付け根",
    meaning: "愛情、活力、生命力",
    fullDesc: "張りがあるほどエネルギッシュで愛情豊か。人を温める力がある。魅力的。",
    flatDesc: "張りが乏しいと冷たい印象、活力不足。",
  },
  moon: {
    name: "月丘",
    nameEn: "Mount of Moon",
    position: "手首近く・小指側",
    meaning: "想像力、直感、スピリチュアル",
    fullDesc: "張りがあるほど想像力と直感力が強い。創作や企画に向く。",
    flatDesc: "張りが乏しいと現実的すぎて想像力に欠ける。",
  },
  marsLower: {
    name: "第一火星丘",
    nameEn: "Lower Mars",
    position: "親指側の中段",
    meaning: "勇気、行動力、闘争心",
    fullDesc: "張りがあるほど積極性と攻めの力が強い。",
    flatDesc: "張りが乏しいと攻める力が弱い。",
  },
  marsUpper: {
    name: "第二火星丘",
    nameEn: "Upper Mars",
    position: "小指側の中段",
    meaning: "粘り強さ、忍耐力、守りの力",
    fullDesc: "張りがあるほど粘り強く困難に耐える力がある。",
    flatDesc: "張りが乏しいと忍耐力に欠ける。",
  },
  marsPlain: {
    name: "火星平原",
    nameEn: "Plain of Mars",
    position: "手のひら中央",
    meaning: "攻めと守りのバランス",
    fullDesc: "平坦すぎると気性が荒い、凹みすぎると消極的。適度な平坦さがバランスを示す。",
    flatDesc: "手のひら中央の平坦さで攻守のバランスを読む。",
  },
};

// === 5. 左手・右手の意味 ===
const handSides = {
  left: {
    name: "左手",
    meaning: "生まれ持った才能・素質（先天的な運勢）",
    description: "本能的に求める理想、潜在的な可能性、宿命",
  },
  right: {
    name: "右手（利き手）",
    meaning: "努力で手に入れた現在の状態（後天的な運勢）",
    description: "自分の行動や意識によって作られた現実、これからの運勢",
  },
  both: {
    name: "両手比較",
    meaning: "左手に良い線→生まれ持った才能、右手に良い線→努力で運を掴んだ",
    description: "両手とも良い線があれば才能と努力の両方に恵まれている。左右で線の位置がほぼ一致すれば理想が現実になりやすい。",
  },
};

// === 6. 手相の見方の基本ステップ ===
const readingSteps = [
  { step: 1, action: "見る手を決める", detail: "これからの運勢なら右手、生まれ持った資質なら左手。できれば両手を見比べる。" },
  { step: 2, action: "手の形を確認", detail: "手のひらの形（四角い/長方形）と指の長さ（長い/短い）で4タイプ（地・火・風・水）を判定。" },
  { step: 3, action: "三大基本線をチェック", detail: "生命線・知能線・感情線を、長さ→濃さ→乱れの順にチェック。性格と体質の土台がわかる。" },
  { step: 4, action: "縦の線と丘で肉づけ", detail: "運命線・太陽線・財運線と、丘の張り、特殊紋を見て、仕事運・金運・個性を重ねていく。" },
  { step: 5, action: "補助線・特殊線を確認", detail: "結婚線・健康線・旅行線、ますかけ線・神秘十字線などの特殊な相をチェック。" },
  { step: 6, action: "印・紋を探す", detail: "星紋・魚紋・島・十字・四角・三角などの印が線上や丘にあるか確認。" },
];

// === 7. 年齢の読み方 ===
const ageReading = {
  lifeLine: "生命線は親指側の付け根からスタートし、手首方向へ。起点＝幼少期、終点＝晩年。島や切れの位置で年齢を推定。",
  fateLine: "運命線は手首（若年期）から中指（晩年）へ。切れ目や変化の位置で転機の年齢を読む。",
  marriageLine: "感情線に近い＝20代前半（早婚）、中間＝28〜32歳、小指寄り＝40歳以降（晩婚）。",
};

// === 8. 線の濃さ・質の意味 ===
const lineQuality = {
  deep: { name: "濃い・はっきり", meaning: "その線の意味が強く現れる。確固たる意志や能力。" },
  faint: { name: "薄い・弱い", meaning: "その線の意味が弱い、またはまだ発達途中。可能性はあるが未開花。" },
  clear: { name: "クリア・一本筋", meaning: "迷いがなく、その分野で安定している。" },
  chained: { name: "鎖状", meaning: "繊細さ、心の揺れ、不安定さ。休息やケアが必要。" },
  broken: { name: "切れている", meaning: "変化、転機、断絶。新しいフェーズへの移行。" },
  forked: { name: "二股・分岐", meaning: "選択肢の複数化、多角性、柔軟性。" },
  branched: { name: "枝分かれ", meaning: "上向き枝＝吉（成長）、下向き枝＝注意（衰退）。" },
};
